[advisories]
ignore = [
    { id = "RUSTSEC-2024-0384", reason = "`instant` is unmaintained but dependencies haven't updated passed it yet" }
]

[licenses]
# List of explicitly allowed licenses
# See https://spdx.org/licenses/ for list of possible licenses
# [possible values: any SPDX 3.11 short identifier (+ optional exception)].
allow = [
    "MIT",
    "MIT-0",
    "Apache-2.0",
    "BSD-2-Clause",
    "BSD-3-Clause",
    "Zlib",
    "CC0-1.0",
    "ISC",
    "Unicode-3.0",
]
confidence-threshold = 1.0
exceptions = [
    # Marked as `publish=false` and thus `licenses.private.ignore=true` below
    # { allow = ["GPL-3.0"], name = "mechaenetia_client", version = "*" },
    # { allow = ["GPL-3.0"], name = "mechaenetia_client_wgpu", version = "*" },
    # { allow = ["GPL-3.0"], name = "mechaenetia_engine", version = "*" },
    # { allow = ["GPL-3.0"], name = "mechaenetia_server", version = "*" },
    # { allow = ["GPL-3.0"], name = "mechaenetia_server_dedicated", version = "*" },
    # { allow = ["GPL-3.0"], name = "mechaenetia_utils", version = "*" },
    # { allow = ["GPL-3.0"], name = "xtask", version = "*" },
]

[licenses.private]
ignore = true

[bans]
wildcards = "deny"

# TODO:  Wtf bevy... like really?!?  Check this later to remove these when that's fixed...
skip = [
    { name = "base64" },
    { name = "bit-set" },
    { name = "bit-vec" },
    { name = "bitflags" },
    { name = "cfg_aliases" },
    { name = "core-foundation" },
    { name = "event-listener" },
    { name = "fixedbitset" },
    { name = "hashbrown" },
    { name = "inotify" },
    { name = "ndk" },
    { name = "ndk-sys" },
    { name = "redox_syscall" },
    { name = "regex-automata" },
    { name = "regex-syntax" },
    { name = "ttf-parser" },
    { name = "windows" },
    { name = "windows-core" },
    { name = "windows-implement" },
    { name = "windows-interface" },
    { name = "windows-result" },
    { name = "windows-strings" },
    { name = "windows-sys" },
    { name = "windows-targets" },
    { name = "windows_aarch64_gnullvm" },
    { name = "windows_aarch64_msvc" },
    { name = "windows_i686_gnu" },
    { name = "windows_i686_gnullvm" },
    { name = "windows_i686_msvc" },
    { name = "windows_x86_64_gnu" },
    { name = "windows_x86_64_gnullvm" },
    { name = "windows_x86_64_msvc" },
]

[sources]
unknown-registry = "deny"
unknown-git = "deny"
