[package]
name = "mechaenetia_utils"
edition = "2024"
rust-version = "1.85"
publish = false
version.workspace = true
authors.workspace = true
license.workspace = true

[dependencies]
clap.workspace = true
tracing.workspace = true
"tracing-subscriber".workspace = true
