[package]
name = "mechaenetia_utils"
edition = "2021"
version.workspace = true
authors.workspace = true
license.workspace = true

[dependencies]
clap.workspace = true
tracing.workspace = true
"tracing-subscriber".workspace = true
