[package]
name = "mechaenetia_client"
edition = "2024"
rust-version = "1.85"
publish = false
version.workspace = true
authors.workspace = true
license.workspace = true

[dependencies]
bevy.workspace = true
mechaenetia_engine.workspace = true
tracing.workspace = true

