[package]
name = "xtask"
edition = "2021"
version.workspace = true
authors.workspace = true
license.workspace = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow.workspace = true
fs-err = "2.9.0"
# Serde is a bit heavy to compile but so valuable...
serde = { version = "1", features = ["derive"] }
serde_json = "1"
